name: Build and Deploy .NET API

on:
  push:
    branches:
      - feature/*
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./LISCare.API
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./LISCare.API
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./LISCare.API

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'   # Only deploy from main branch
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./LISCare.API
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./LISCare.API/publish
