name: Build and Deploy .NET API

on:
  push:
    branches:
      - feature/*
      - develop
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files for debug
        run: ls -R ./LISCareLimited

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./LISCareLimited

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./LISCareLimited

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./LISCareLimited

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------------
      # Determine environment based on branch
      # ------------------------
      - name: Set environment
        id: set-env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "ENV=Production" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/qa" ]]; then
            echo "ENV=QA" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "ENV=Development" >> $GITHUB_ENV
          else
            echo "ENV=Development" >> $GITHUB_ENV
          fi
          echo "Branch: ${GITHUB_REF}, Environment: $ENV"

      # ------------------------
      # Copy correct appsettings.{env}.json
      # ------------------------
      - name: Copy appsettings for environment
        run: |
          echo "Using appsettings.$ENV.json as appsettings.json"
          cp ./LISCareLimited/appsettings.$ENV.json ./LISCareLimited/appsettings.json

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Publish .NET API (with all dependencies)
        run: |
          dotnet publish ./LISCareLimited/LISCareLimited.csproj \
            --configuration Release \
            --output ./LISCareLimited/publish \
            --no-restore
        working-directory: ./LISCareLimited

      - name: Deploy to Azure WebApp (Production)
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: dev-lis-care-api        # Azure WebApp name
          package: ./LISCareLimited/publish
          slot-name: production
