name: Build and Deploy .NET API

on:
  push:
    branches:
      - feature/*
      - develop
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files for debug
        run: ls -R ./LISCareLimited

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # ------------------------
      # Restore dependencies (fail if any package is missing)
      # ------------------------
      - name: Restore dependencies
        run: |
          echo "Restoring NuGet packages..."
          dotnet restore ./LISCareLimited/LISCareLimited.csproj --no-cache
        shell: bash

      - name: Build
        run: dotnet build --configuration Release ./LISCareLimited/LISCareLimited.csproj

      - name: Test
        run: dotnet test --no-build --verbosity normal ./LISCareLimited/LISCareLimited.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------------
      # Determine environment based on branch
      # ------------------------
      - name: Set environment
        id: set-env
        run: |
          case "${GITHUB_REF}" in
            refs/heads/main) echo "ENV=Production" >> $GITHUB_ENV ;;
            refs/heads/qa) echo "ENV=QA" >> $GITHUB_ENV ;;
            refs/heads/develop) echo "ENV=Development" >> $GITHUB_ENV ;;
            *) echo "ENV=Development" >> $GITHUB_ENV ;;
          esac
          echo "Branch: ${GITHUB_REF}, Environment: $ENV"

      # ------------------------
      # Copy correct appsettings.{env}.json
      # ------------------------
      - name: Copy appsettings for environment
        run: |
          if [ -f ./LISCareLimited/appsettings.$ENV.json ]; then
            echo "Using appsettings.$ENV.json"
            cp ./LISCareLimited/appsettings.$ENV.json ./LISCareLimited/appsettings.json
          else
            echo "Warning: appsettings.$ENV.json not found, using default appsettings.json"
          fi

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      # ------------------------
      # Publish .NET API
      # ------------------------
      - name: Publish .NET API
        run: |
          echo "Publishing .NET project..."
          dotnet publish ./LISCareLimited/LISCareLimited.csproj \
            --configuration Release \
            --output ./LISCareLimited/publish \
            --no-restore
        shell: bash

      # ------------------------
      # Deploy only from main branch
      # ------------------------
      - name: Deploy to Azure WebApp (Production)
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: dev-lis-care-api
          package: ./LISCareLimited/publish
          slot-name: production
